version: 0.2
phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - curl -JLO https://github.com/docker/buildx/releases/download/v0.4.2/buildx-v0.4.2.linux-amd64
      - mkdir -p ~/.docker/cli-plugins
      - mv buildx-v0.4.2.linux-amd64 ~/.docker/cli-plugins/docker-buildx
      - chmod a+rx ~/.docker/cli-plugins/docker-buildx
      - docker run --privileged --rm tonistiigi/binfmt --install all
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image... 
      - mkdir -p "${CODEBUILD_SRC_DIR}/cache/docker"
      - docker buildx create --use --driver=docker-container
      - docker buildx build .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...